org.gradle.jvmargs=-Xmx8G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=false
org.gradle.configuration-cache=true


neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
loader_version_range=[1,)

## Mod Properties

mod_id=aero_player_tilt
mod_name=Aeronautics Player Tilt
mod_authors=MrLemonHog, Playsi_
mod_license=CC-BY-ND-4.0
mod_version=0.1.3
mod_group_id=com.mlh.aero_player_tilt

## DEPS version
create_version = 6.0.10-280
ponder_version = 1.0.82
flywheel_version = 1.0.6
registrate_version=MC1.21-1.3.0+67
sodium_version = mc1.21.10-0.7.3-neoforge

aeronautics_version = 1.3.0+mc1.21.1
## aeronautics inner jars
aeronautics_bundle_version = 1.3.0
sable_version = 2.0.3
sable_companion_version = 1.4.2
acs_version = 1.4.0
